M48
; DRILL file {KiCad 9.0.0} date 2025-03-06T01:47:33+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-06T01:47:33+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X156.32Y-100.0
T2
X185.89Y-103.81
X190.97Y-96.19
M30
